trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm install
  displayName: 'Frontend Install'

- script: |
    cd backend
    npm install
  displayName: 'Backend Install'